@isTest
public class OF_Billing_Outbound_Schema2_Test{
    public static testMethod void OF_Billing_Outbound_Schema2Method(){
        OF_Billing_Outbound_Schema2.BillingAgreementManagerResponseType  agree = new OF_Billing_Outbound_Schema2.BillingAgreementManagerResponseType  ();
        OF_Billing_Outbound_Schema2.BillingAgreementManagerRequestType agree1 = new OF_Billing_Outbound_Schema2.BillingAgreementManagerRequestType ();

        
    }
}