@isTest
private class OF_PP_WS_VLAN_OM_Response_TEST {

	private static testMethod void test() 
	{
        String ID_NOTIFICA;
        String ESITO;
        String CODICE_MOTIVAZIONE;
        String MOTIVAZIONE;
        String[] ID_NOTIFICA_type_info = new String[]{'ID_NOTIFICA','http://www.tibco.com/schemas/OLO_Gat_ChangeOrder/SharedResources/CommonSchema/PreProvisioning/Esito.xsd3',null,'1','1','false'};
        String[] ESITO_type_info = new String[]{'ESITO','http://www.tibco.com/schemas/OLO_Gat_ChangeOrder/SharedResources/CommonSchema/PreProvisioning/Esito.xsd3',null,'1','1','false'};
        String[] CODICE_MOTIVAZIONE_type_info = new String[]{'CODICE_MOTIVAZIONE','http://www.tibco.com/schemas/OLO_Gat_ChangeOrder/SharedResources/CommonSchema/PreProvisioning/Esito.xsd3',null,'0','1','false'};
        String[] MOTIVAZIONE_type_info = new String[]{'MOTIVAZIONE','http://www.tibco.com/schemas/OLO_Gat_ChangeOrder/SharedResources/CommonSchema/PreProvisioning/Esito.xsd3',null,'0','1','false'};
        String[] apex_schema_type_info = new String[]{'http://www.tibco.com/schemas/OLO_Gat_ChangeOrder/SharedResources/CommonSchema/PreProvisioning/Esito.xsd3','true','false'};
        String[] field_order_type_info = new String[]{'ID_NOTIFICA','ESITO','CODICE_MOTIVAZIONE','MOTIVAZIONE'};
        
	    OF_PP_WS_VLAN_OM_Response.Esito_element wrap = new  OF_PP_WS_VLAN_OM_Response.Esito_element();
	}
}