@isTest
private class OF_PP_WS_VLAN_OM_Classi_TEST {

	private static testMethod void test() 
	{
	    Test.startTest();
	    
	    OF_PP_WS_VLAN_OM_Classi.ServiziOpzionali servOpz = new OF_PP_WS_VLAN_OM_Classi.ServiziOpzionali();
	    OF_PP_WS_VLAN_OM_Classi.ServiziOpzionali_element serv_opz_el = new OF_PP_WS_VLAN_OM_Classi.ServiziOpzionali_element();
	    OF_PP_WS_VLAN_OM_Classi.Activation_PreProvisioning_OpenStream_element act_pp = new OF_PP_WS_VLAN_OM_Classi.Activation_PreProvisioning_OpenStream_element();
	    
	    Test.stopTest();
	}
}